# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognition', '0001_initial'),
        ('vulnerability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affected_elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evidences_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_e', models.ImageField(upload_to='images_evidences')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_logo', models.ImageField(upload_to='logo_client')),
                ('introduction', models.TextField()),
                ('objetive', models.TextField()),
                ('recognition_description', models.TextField()),
                ('affected_elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Affected_elements')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Client')),
                ('evidences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Evidences_images')),
            ],
        ),
        migrations.CreateModel(
            name='Title_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type_pentest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pent', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Title_report'),
        ),
        migrations.AddField(
            model_name='report',
            name='recognition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.Recognition'),
        ),
        migrations.AddField(
            model_name='report',
            name='type_pentest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Type_pentest'),
        ),
        migrations.AddField(
            model_name='report',
            name='vulnerability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerability.Vulnerability'),
        ),
    ]
