# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images_recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images_evidences')),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('images_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.Images_recognition')),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls_i', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='recognition',
            name='urls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.Urls'),
        ),
    ]
